FROM node:7.10

COPY ./map /app/map
COPY ./node_modules /app/node_modules
COPY ./img /app/img
COPY package.json /app
COPY server.js /app

WORKDIR /app

EXPOSE 9002
CMD ["npm", "install"]
CMD ["node", "server.js"]